import tkinter as tk
from tkinter import messagebox

def add_task():
    task = entry.get()
    if task:
        listbox.insert(tk.END, task)
        entry.delete(0, tk.END)
    else:
        messagebox.showwarning("Warning", "Please enter a task.")

def remove_task():
    selected_task_index = listbox.curselection()
    if selected_task_index:
        listbox.delete(selected_task_index)
    else:
        messagebox.showwarning("Warning", "Please select a task to remove.")

# GUI Setup
app = tk.Tk()
app.title("To-Do List")

# Entry for adding tasks
entry = tk.Entry(app, width=30)
entry.pack(pady=10)

# Button to add task
add_button = tk.Button(app, text="Add Task", command=add_task)
add_button.pack(pady=5)

# Listbox to display tasks
listbox = tk.Listbox(app, selectmode=tk.SINGLE, height=10, width=30)
listbox.pack(pady=10)

# Button to remove selected task
remove_button = tk.Button(app, text="Remove Task", command=remove_task)
remove_button.pack(pady=5)

# Start the application
app.mainloop()
